# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-28 09:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myfirstblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='date',
            field=models.DateField(default=datetime.datetime(2016, 4, 28, 9, 12, 32, 309570, tzinfo=utc)),
        ),
    ]
