# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-28 09:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myfirstblog', '0002_article_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 28, 9, 13, 41, 496630, tzinfo=utc)),
        ),
    ]
