# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-28 09:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myfirstblog', '0004_remove_article_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='date_now',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 28, 9, 33, 50, 68804, tzinfo=utc)),
        ),
    ]
