# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-28 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfirstblog', '0008_auto_20160428_0939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='date_now',
        ),
        migrations.AddField(
            model_name='article',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
