# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-28 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfirstblog', '0009_auto_20160428_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='user',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
